services:
  transaction_service:
    build:
      context: ./transaction_service
      dockerfile: Dockerfile
    image: dfoddav/transaction_service:latest
    ports:
      - "${TRANSACTION_SERVICE_PORT:-8000}:8000"
    env_file:
      - ./transaction_service/.env.docker

  authentication_service:
    build:
      context: ./authentication_service
      dockerfile: Dockerfile
    image: dfoddav/authentication_service:latest
    ports:
      - "${AUTHENTICATION_SERVICE_PORT:-8001}:8001"
    env_file:
      - ./authentication_service/.env.docker

  backend_service:
    build:
      context: ./backend_service
      dockerfile: Dockerfile
    image: dfoddav/backend_service:latest
    ports:
      - "${BACKEND_SERVICE_PORT:-8002}:8002"
    env_file:
      - ./backend_service/.env.docker

  message_queue_redis:
    image: redis:7.4-alpine
    container_name: message_queue_redis
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --requirepass message_queue_password

  message_queue:
    build:
      context: ./message_queue
      dockerfile: Dockerfile
    image: dfoddav/message_queue:latest
    ports:
      - "${MESSAGE_QUEUE_PORT:-8003}:8003"
    env_file:
      - ./message_queue/.env.docker
    depends_on:
      - message_queue_redis
