services:
  transaction_service:
    build:
      context: ./transaction_service
      dockerfile: Dockerfile
    image: dfoddav/transaction_service:latest
    ports:
      - "${TRANSACTION_SERVICE_PORT:-8000}:8000"
    env_file:
      - .env

  authentication_service:
    build:
      context: ./authentication_service
      dockerfile: Dockerfile
    image: dfoddav/authentication_service:latest
    ports:
      - "${AUTHENTICATION_SERVICE_PORT:-8001}:8001"
    env_file:
      - .env

  backend_service:
    build:
      context: ./backend_service
      dockerfile: Dockerfile
    image: dfoddav/backend_service:latest
    ports:
      - "${BACKEND_SERVICE_PORT:-8002}:8002"
    env_file:
      - .env

  message_queue_redis:
    image: redis:7.4-alpine
    container_name: message_queue_redis
    ports:
      - "6379:6379"
    command: redis-server --save ${REDIS_SAVE_INTERVAL:-20} ${REDIS_SAVE_PER_CHANGES:-1} --requirepass ${REDIS_PASSWORD}

  message_queue:
    build:
      context: ./message_queue
      dockerfile: Dockerfile
    image: dfoddav/message_queue:latest
    ports:
      - "${MESSAGE_QUEUE_PORT:-8003}:8003"
    env_file:
      - .env
    depends_on:
      - message_queue_redis
