services:
  transaction_service:
    build:
      context: ./transaction_service
      dockerfile: Dockerfile
    image: dfoddav/transaction_service:latest
    ports:
      - "${TRANSACTION_SERVICE_PORT:-8000}:8000"
    env_file:
      - ./transaction_service/.env.docker

  authentication_service:
    build:
      context: ./authentication_service
      dockerfile: Dockerfile
    image: dfoddav/authentication_service:latest
    ports:
      - "${AUTHENTICATION_SERVICE_PORT:-8001}:8001"
    env_file:
      - ./authentication_service/.env.docker

  backend_service:
    build:
      context: ./backend_service
      dockerfile: Dockerfile
    image: dfoddav/backend_service:latest
    ports:
      - "${BACKEND_SERVICE_PORT:-8002}:8002"
    env_file:
      - ./backend_service/.env.docker
