services:
  message_queue_redis:
    image: redis:7.4-alpine
    container_name: message_queue_redis
    ports:
      - "6379:6379"
    command: redis-server --save ${REDIS_SAVE_INTERVAL:-20} ${REDIS_SAVE_PER_CHANGES:-1} --requirepass ${REDIS_PASSWORD}

  message_queue:
    build:
      context: .
      dockerfile: Dockerfile
    image: dfoddav/message_queue:latest
    ports:
      - "${MESSAGE_QUEUE_PORT:-8003}:8003"
    env_file:
      - .env.docker
    depends_on:
      - message_queue_redis
